### ISSUE TITLE
subfigure conflict with "Command \c@lofdepth already defined. \newcounter{lofdepth}"

### ISSUE THREAD

**Issue by HoxinhLuo** [FrankSFLYS/usstthesis#1]
1. Command \c@lofdepth already defined. \newcounter{lofdepth}
2. Command \c@lotdepth already defined. \newcounter{lotdepth}
![Snipaste_2019-05-12_14-25-03](https://user-images.githubusercontent.com/23025747/57578632-8841c580-74c2-11e9-8cf6-ae66da7464a3.png)

**Comment by HoxinhLuo** [comment]
I found the solution of the problem. That is "My adding the 'subfigure' option in the usstthesis.cls file in the \RequiredPackage{tofloft}, which become to \RequiredPackage[subfigure]{tocloft}"
![Snipaste_2019-05-12_14-36-55](https://user-images.githubusercontent.com/23025747/57578682-7e6c9200-74c3-11e9-9ab1-82b81bf80951.png)

**Comment by FrankSFLYS** [comment]
OK, I will add this as the default option.

**Comment by firminoazevedo** [comment]
\makeatletter
\let\c@lofdepth\relax
\let\c@lotdepth\relax
\makeatother
\usepackage{subfigure}

tente isso, comigo funcionou

**Comment by wzm2256** [comment]
> \RequiredPackage[subfigure]{tocloft}

Note:
``\RequirePackage[subfigure]{tocloft}`` not ``\RequiredPackage[subfigure]{tocloft}``

**Comment by asmwarrior** [comment]
> \makeatletter \let\c@lofdepth\relax \let\c@lotdepth\relax \makeatother \usepackage{subfigure}
> 
> tente isso, comigo funcionou

This indeed fix the build error, thanks
