### ISSUE TITLE
关于加粗的问题

### ISSUE THREAD

**Issue by xinxijishuwyq** [FrankSFLYS/usstthesis#4]
> 包附带的三种字体使用方法分别为：华文中宋加粗：{\bZhongsong 华文中宋粗体}，华文中宋正体：{\Zhongsong 华文中宋}，宋体加粗：{\bSong 宋体粗体}，楷体加粗：{\bKai 楷体粗体}。注意： 如果要加粗的字体中同时有中英文，还需要再加上 \bfseries，此时编译会报字体警告，可以忽略。

但是我试了下，使用\bSong 出现报错。
![image](https://user-images.githubusercontent.com/1755898/81297660-2badc200-90a6-11ea-990d-eb62dfe40184.png)

**Comment by xinxijishuwyq** [comment]
![image](https://user-images.githubusercontent.com/1755898/81298784-dbcffa80-90a7-11ea-9aaa-feba321d58c8.png)

另外，中文”关键词“的加重似乎过浅（左是往年别人的，右边是刚刚用模板生成的）--

**Comment by FrankSFLYS** [comment]
确实，这里的说明和代码已经不一致了，现在使用宋体加粗的话直接 `{\bfseries 加粗bold文字}` 就可以了，由于在正文中无需使用华文中宋和楷体的粗体，所以 `\bZhongsong`、`\bKai` 和 `\Zhongsong` 也失效了。

宋体粗体不够粗的问题我对比了一下，确实存在。

**Comment by FrankSFLYS** [comment]
已经更新解决了，如果还有问题的话可以新开 issue

**Comment by FrankSFLYS** [comment]
由于 Github 访问比较慢，你也可以到 [Gitee](https://gitee.com/MkSwQi/usstthesis) 上进行讨论。

**Comment by xinxijishuwyq** [comment]
> 由于 Github 访问比较慢，你也可以到 [Gitee](https://gitee.com/MkSwQi/usstthesis) 上进行讨论。

问题已解决。对我来说本来就是路由器挂着梯子，所以上gayhub的速度并没有问题，并且我的论文也是丢到gayhub的私人仓库上处理的。如果对你来说上Gitee更方便的话，我可以去Gitee讨论--

**Comment by FrankSFLYS** [comment]
那就在 Github 上好了，现在 Github 的关注度更高一点，Gitee 用户太少了。
