### ISSUE TITLE
签字图片插入到承诺书处

### ISSUE THREAD

**Issue by xinxijishuwyq** [FrankSFLYS/usstthesis#9]
请问是否有办法将签字图片插入到承诺书处。。

**Comment by xinxijishuwyq** [comment]
用Acrobat Reader DC直接插入签名到pdf了

**Comment by FrankSFLYS** [comment]
我当时用的 PDF24

**Comment by xinxijishuwyq** [comment]
我最后用Adobe那个什么pro的七天试用，把扫描全能王拍的图片覆盖上去了。。

frank.xin <notifications@github.com> 于 2020年5月27日周三 18:04写道：
